# Generated by Django 6.0.7 on 2026-09-25 16:46

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_curso_descripcion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='textoblog',
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name='curso',
            name='descripcion',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
