# Generated by Django 6.0.7 on 2026-09-26 02:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_blog_textoblog_alter_curso_descripcion'),
    ]

    operations = [
        migrations.CreateModel(
            name='Docente',
            fields=[
                ('iddocente', models.AutoField(primary_key=True, serialize=False)),
                ('priNombre', models.CharField(max_length=50)),
                ('segNombre', models.CharField(blank=True, max_length=50, null=True)),
                ('terNombre', models.CharField(blank=True, max_length=50, null=True)),
                ('apePaterno', models.CharField(max_length=50)),
                ('apeMaterno', models.CharField(max_length=50)),
                ('dni', models.CharField(max_length=20, unique=True)),
                ('direccion', models.CharField(blank=True, max_length=50, null=True)),
                ('telefono', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Especialidad',
            fields=[
                ('idEspecialidad', models.AutoField(primary_key=True, serialize=False)),
                ('nomEspecialidad', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='curso',
            name='docente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cursos', to='core.docente'),
        ),
        migrations.AddField(
            model_name='docente',
            name='idEspecialidad',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='docentes', to='core.especialidad'),
        ),
        migrations.CreateModel(
            name='Nota',
            fields=[
                ('idnota', models.AutoField(primary_key=True, serialize=False)),
                ('valor_nota', models.DecimalField(decimal_places=1, max_digits=9)),
                ('fec_crea', models.DateField()),
                ('idmatricula', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notas', to='core.matricula')),
            ],
        ),
    ]
