# Generated by Django 6.0.7 on 2026-09-26 03:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_docente_especialidad_curso_docente_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='curso',
            name='docente',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='cursos', to='core.docente'),
        ),
    ]
